### ISSUE TITLE
EFI/BIOS hybrid boot

### ISSUE THREAD

**Issue by kepebi** [adi1090x/uGRUB#6]
Hi. To be able to boot UEFI / BIOS, do I need to run all three commands to install GRUB? If so, what else needs to be done? Thanks.

**Comment by sentinm** [comment]
> Hi. To be able to boot UEFI / BIOS, do I need to run all three commands to install GRUB? If so, what else needs to be done? Thanks.

![Screenshot_20220303_094400.jpg](https://user-images.githubusercontent.com/79321771/156495078-bfc69ae4-2a93-486b-a449-11be332eb9a0.jpg)

Just this xd.
